@HostAddress = http://localhost:5101

GET {{HostAddress}}/hello-demo

###

# @name custom
GET {{HostAddress}}/new-feature

###

POST {{HostAddress}}/endpoints/hello/postdata
Content-Type: application/json
{
  "hello":"vipwan",
  "world": "today is ."
}
